Repository tensorflow/community, pull requests merged in 2019-10, with the labels that each got.

#151 RFC: StructTensor
  rfcs/20190910-struct-tensor.md
  rfcs/20190910-struct-tensor/arrow_example_1.png
  rfcs/20190910-struct-tensor/arrow_example_2.png
  rfcs/20190910-struct-tensor/feature_extraction_in_model.png
  rfcs/20190910-struct-tensor/integration_with_other_formats.png
  rfcs/20190910-struct-tensor/pydict_to_struct_tensor.png
  rfcs/20190910-struct-tensor/python_vs_struct_tensor_encoding.png
  rfcs/20190910-struct-tensor/recipe_schema.png
  rfcs/20190910-struct-tensor/struct_5.png
Labels: RFC: Proposed, cla: yes

#144 RFC: TFX Resolver
  rfcs/20190828-tfx-resolver.md
Labels: RFC: Accepted, TFX, cla: yes

#136 RFC: TFX Iterative Notebook Proposal
  rfcs/20190815-tfx-notebook.md
Labels: cla: yes

#139 RFC: Native SavedModel execution in Node.js
  rfcs/20190821-nodejs-saved-model.md
Labels: RFC: Proposed, TF.JS, cla: yes

#146 RFC: TFX Generic Container-based Component
  rfcs/20190904-tfx-generic-container-based-component.md
Labels: RFC: Proposed, TFX, cla: yes

#150 Update CHARTER.md
  sigs/mlir/CHARTER.md
Labels: cla: yes

#142 Fix 404
  sigs/testing/faq.md
Labels: cla: yes

#123 Update Release process of SIG IO to use Dropbox
  sigs/io/RELEASE.md
Labels: cla: yes

#105 Update CHARTER.md
  sigs/micro/CHARTER.md
Labels: cla: yes

#155 Addons: List all files which are related to tf version
  sigs/addons/RELEASE.md
Labels: cla: yes

#82 Update 20181016-optimizer-unification.md
  rfcs/20181016-optimizer-unification.md
Labels: cla: yes

#80 Update 20180827-api-names.md
  rfcs/20180827-api-names.md
Labels: cla: yes

#51 Small typo
  sigs/build/tensorflow-testing.md
Labels: cla: yes

#75 Formatting tweaks.
  sigs/testing/README.md
Labels: cla: yes

#98 RFC: Tokenization API & Initial Implementations
  rfcs/20190430-tokenization-conventions.md
Labels: RFC: Proposed, cla: yes

#124 RFC: On-Device Training with TensorFlow Lite
  rfcs/20190722-tflite-training.md
  rfcs/20190722-tflite-training/roadmap.png
  rfcs/20190722-tflite-training/trans1.png
  rfcs/20190722-tflite-training/trans2.png
Labels: RFC: Proposed, cla: yes

#100 RFC: TensorCord Variant Object
  rfcs/20190501-tf-tensor-cord.md
Labels: RFC: Proposed, cla: yes

#135 RFC: Project versioning in the TensorFlow organization
  rfcs/20190816-tf-project-versioning.md
Labels: RFC: Proposed, cla: yes

#126 RFC: Best practices for custom operations in TensorFlow
  rfcs/20190726-custom-ops.md
Labels: 2.0, RFC: Proposed, cla: yes

#163 Addons Release: remove no longer existing file to update
  sigs/addons/RELEASE.md
Labels: cla: yes

#164 Update SIG I/O release team
  sigs/io/RELEASE.md
Labels: cla: yes

#156 RFC: TFX Generic Container Component Execution
  rfcs/20190829-tfx-container-component-execution.md
  rfcs/20190829-tfx-container-component-execution/tfx-container-execution-classes.png
  rfcs/20190829-tfx-container-component-execution/tfx-k8s-container-execution.png
  rfcs/20190829-tfx-container-component-execution/tfx-local-container-execution.png
Labels: RFC: Proposed, TFX, cla: yes

#166 Update 20190904-tfx-generic-container-based-component.md
  rfcs/20190904-tfx-generic-container-based-component.md
Labels: RFC: Accepted, cla: yes
