Repository tensorflow/community, pull requests merged in 2019-04, with the labels that each got.

#85 Update addons owners
  sigs/addons/CHARTER.md
Labels: cla: yes

#78 Created a FAQ for TF 2.0.
  sigs/testing/faq.md
Labels: cla: yes

#86 Request and charter for SIG JVM
  sigs/jvm/CHARTER.md
  sigs/jvm/SIG-request.md
Labels: cla: yes

#69 RFC: TF on Demand Project
  rfcs/20190225-tf-on-demand.md
Labels: RFC: Accepted, SIG Build, cla: yes

#34 RFC: SavedModel Save/Load in 2.x
  rfcs/20181116-saved-model.md
Labels: 2.0, RFC: Accepted, cla: yes

#81 Update 20180920-unify-rnn-interface.md
  rfcs/20180920-unify-rnn-interface.md
Labels: cla: yes

#71 Update while_v2 design doc
  rfcs/20180821-differentiable-functional-while.md
Labels: cla: yes

#94 Update TF 2.0 FAQ to link to TensorBoard TF 2.0 tutorial
  sigs/testing/faq.md
Labels: cla: yes
