Repository tensorflow/community, pull requests merged in 2021-03, with the labels that each got.

#360 Update CHARTER.md
  sigs/tf.js/CHARTER.md
Labels: cla: yes

#340 Update SIG Recommener contacts
  sigs/recommenders/CHARTER.md
Labels: cla: yes

#363 RFC: Create SIG TFX-Addons
  rfcs/20210302-sig-tfx-addons.md
Labels: RFC: Proposed, cla: yes

#366 Create CHARTER.md for SIG TFX-Addons
  sigs/tfx-addons/CHARTER.md
Labels: cla: yes

#365 Update contacts in TensorBoard community charter.
  sigs/tensorboard/CHARTER.md
Labels: cla: yes

#367 Update CODEOWNERS
  CODEOWNERS
Labels: cla: yes

#357 Updating contacts for SIG
  sigs/swift/CHARTER.md
Labels: cla: yes

#369 Moving Swift SIG to archive mode
  sigs/archived/swift/CHARTER.md
Labels: cla: yes

#346 RFC: Enhancing determinism in TF
  rfcs/20210119-determinism.md
Labels: RFC: Proposed, cla: yes

#355 RFC: Setting GRPC_FAIL_FAST to use_caller by Default
  rfcs/20210218-grpc-fail-fast-use-caller.md
Labels: RFC: Accepted, cla: yes
